permalink: /writings/:title/

exclude: ['README.md', 'gemfile', 'Gemfile.lock']
highlighter: pygments

markdown: rdiscount

title: aaron stacy's writings
tagline: not in the face
author:
  name: Aaron Stacy
  github: aaronj1335
  twitter: '@aaronj1335'

production_url: 'http://aaronstacy.com'

comments:
  provider: disqus
  disqus:
    short_name: aaronstacydotcom

emoji_dir: assets/images/emoji
