exclude: ['README.md', 'build.py', 'kramdown.py', 'pyproject.toml', 'uv.lock']

title: aaron stacy's writings
tagline: not in the face
author:
  name: Aaron Stacy
  github: aaronj1335
  twitter: '@aaronj1335'

production_url: 'http://aaronstacy.com'

comments:
  provider: disqus
  disqus:
    short_name: aaronstacydotcom

emoji_dir: assets/images/emoji
