permalink: /writings/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

markdown: rdiscount

title: aaron stacy's writings
tagline: not in the face
author:
  name: Aaron Stacy
  github: aaronj1335
  twitter: "@aaronj1335"

production_url: "http://aaronstacy.com"

comments:
  provider: disqus
  disqus:
    short_name: aaronstacydotcom
